apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todo-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: dwk-repo
  interval: 10m
  path: ./todo-app
  prune: true
  validation: client
